### ISSUE TITLE
架构RPC通信的方式，目前还不支持通讯加密防破解和通讯拦截篡改

### ISSUE THREAD

**Issue by kerneltravel** [snail007/go-wingui#1]
你们文档里面提到：假设你的app.exe启动之后，访问链接是http://127.0.0.1:9999/index。
这种通信方式也允许普通浏览器直接打开访问。最好能支持https通信方式，而且限定客户端只允许key符合的客户端与go服务端通讯。以达到防止通讯破解。

另外，嵌入的js文件，能静态二进制编译到可执行文件里面吗？ 这样的话生产环境部署的时候源码文件都不会显示，看起来会更像本地化的软件那样。

**Comment by snail007** [comment]
1.https的问题,start_url支持https.
2.key的问题,你可以在start_url里面加上key参数,后面的web服务校验即可.
3.你说的js是web服务端还是srv.exe的,srv.exe暴漏js出来是为了更自由定制化,如果是你自己的web服务,完全可以把js css html打包进二进制文件.有相关的go类库.

**Comment by snail007** [comment]
普通的bs网站怎么保证安全性的？是否采取一样的控制手段？这个内部架构其实也是bs。

**Comment by snail007** [comment]
如果你的web服务绑定127.0.0.1，bs内部通讯都是本机，加上https，其它程序是无法嗅探的。
